config:
  validation: true
  warningsAsErrors: true
  excludes: ''

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'
  ClassNaming:
    excludes: &testFolders
      - '**/test/**'
      - '**/androidTest/**'
  ConstructorParameterNaming:
    excludes: *testFolders

build:
  maxIssues: 0
  weights:
    complexity: 9
    LongParameterList: 9
    comments: 8

console-reports:
  active: true

output-reports:
  active: true

processors:
  active: true

empty-blocks:
  active: true
  severity: error
  EmptyCatchBlock:
    active: true
    severity: info
  EmptyFunctionBlock:
    active: false
    ignoreOverridden: false


complexity:
  TooManyFunctions:
    thresholdInFiles: 10
    excludes:
      - '**/internal/**'
  LongParameterList:
    functionThreshold: 9
    ignoreDefaultParameters: true
  LongMethod:
    threshold: 120
  CognitiveComplexMethod:
    active: true
    threshold: 20
  StringLiteralDuplication:
    active: true
    threshold: 9

style:
  MagicNumber:
    active: false
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
  OptionalWhenBraces:
    active: false
  ForbiddenComment:
    active: true
    allowedPatterns: '(TODO:)|(FIXME:)'
  UnusedParameter:
    active: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false
