name: Android Build

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      #- name: Decode google-services.json
      #  env:
      #    FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      #  run: echo $FIREBASE_JSON > app/google-services.json

      - name: Run Debug Tests
        run: ./gradlew detekt --continue
        #run: ./gradlew build test --continue

      #- name: Upload Test Reports
      #  if: ${{ always() }}
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: test-reports
      #    path: '**/build/reports/tests/'

      - name: Upload Detekt Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: detekt-reports
          path: '**/build/reports/detekt/detekt.sarif'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: '$PROJECT_LOCATION/app/build/reports/detekt/detekt.sarif'
